apiVersion: apps/v1
kind: Deployment
metadata:
  name: vitess-workflow-mon-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-app
  template:
    metadata:
      labels:
        app: test-app
    spec:
      containers:
      - name: test-app
        image: aresox/vitess_workflow_monitor:0.12
        resources:
          limits:
            memory: "256Mi"
            cpu: "200m"
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: vitess-workflow-mon-svc
spec:
  selector:
    app: vitess-workflow-mon-depl
  ports:
  - port: 6000
    targetPort: 5000
  type: LoadBalancer